clc;
clear('all');
rng('default');
warning('off','all');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% SIMULATION CONFIGURATION %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
PARAMETERS = {};
PARAMETERS.SIMULATION = {};
PARAMETERS.SIMULATION.SCENARIO = 2;
PARAMETERS.SIMULATION.TOTAL_TIME = 1e-1;
PARAMETERS.SIMULATION.SAMPLING_TIME = 5E-3;
PARAMETERS.SIMULATION.INITIAL_STATE = 20;
PARAMETERS.SIMULATION.NOISE_MODULE_DB = 0;
PARAMETERS.PLOT = {};
PARAMETERS.PLOT.CREATE_PDF = 0;
PARAMETERS.PLOT.FONT_SIZE = 12;
PARAMETERS.CONTROL = {};
if PARAMETERS.SIMULATION.SCENARIO == 1
    PARAMETERS.CONTROL.K1 = 2;
    PARAMETERS.CONTROL.K2 = 1;
    PARAMETERS.CONTROL.K3 = 1;
    PARAMETERS.CONTROL.MAX = 5;
    PARAMETERS.CONTROL.EPSILON = 2;
elseif PARAMETERS.SIMULATION.SCENARIO == 2
    PARAMETERS.CONTROL.K1 = 4;
    PARAMETERS.CONTROL.K2 = 9;
    PARAMETERS.CONTROL.K3 = 2;
    PARAMETERS.CONTROL.MAX = 5;
    PARAMETERS.CONTROL.EPSILON = 0.1;
elseif PARAMETERS.SIMULATION.SCENARIO == 3
    PARAMETERS.CONTROL.K1 = 4;
    PARAMETERS.CONTROL.K2 = 9;
    PARAMETERS.CONTROL.K3 = 2;
    PARAMETERS.CONTROL.MAX = 5;
    PARAMETERS.CONTROL.EPSILON = 0.1;
else
    PARAMETERS.CONTROL.K1 = 2;
    PARAMETERS.CONTROL.K2 = 1;
    PARAMETERS.CONTROL.K3 = 1;
    PARAMETERS.CONTROL.MAX = 5;
    PARAMETERS.CONTROL.EPSILON = 2;
end
PARAMETERS.CONTROL.LAMBDA = 0.1/PARAMETERS.SIMULATION.SAMPLING_TIME;
PARAMETERS.CONTROL.GAMMA = 0.5*PARAMETERS.CONTROL.LAMBDA; 
PARAMETERS.CONTROL.CHI_1 = PARAMETERS.CONTROL.LAMBDA;
PARAMETERS.CONTROL.CHI_2 = 1;
simulation_time = 0:PARAMETERS.SIMULATION.SAMPLING_TIME:PARAMETERS.SIMULATION.TOTAL_TIME;
PARAMETERS.SIMULATION.TOTAL_STEPS = size(simulation_time, 2);
SIMULATION_DATA = run_simulation(PARAMETERS);
plot_simulation(SIMULATION_DATA, PARAMETERS);
PARAMETERS.CONTROL